### PR TITLE
Fakegato support for Temperature/Humidity Sensors, Motion Sensors and Contact Sensors

### PR DESCRIPTION
**Pull request by SeydX**
Fakegato is a module to emulate Elgato Eve history service in Homebridge accessories, so that it will show in Eve.app

Fakegato: https://github.com/simont77/fakegato-history/blob/master/README.md

This will add Fakegato to Temperature/Humidity Sensors (v1/v2), Motion Sensors (v1/v2) and Contact Sensors 

If you do not want to wait for this pull request, you can already install the version with 'Fakegato' as follows

sudo npm i -g homebridge-mi-aqara-fakegato

### CODE REVIEW

**Comment by tomsteenbakkers** [comment]
When will this be merged with the master?

**Comment by SeydX** [comment]
Screenshots:

f8dd3641-c0c5-48b3-ab84-b9ccb4c4e5b2
b608a19a-c8ac-4049-be71-a758074c0fd7
22e0258d-d281-45c9-a5ea-8bc7912e616a
6c5be631-adc8-4f0e-9470-b529b6ddce5f

**Comment by a900927** [comment]
👍GOOD JOB!

**Comment by SeydX** [comment]
This Version can also be installed with following Command

sudo npm i -g homebridge-mi-aqara-fakegato

Please remove the old Version after installing this Version! You dont need to Change the Config.json

**Comment by SeydX** [comment]
Is now ready to be merge

**Comment by SeydX** [comment]
Latest Screenshot with "Last Activation"

img_3350
img_3351
img_3352
img_3353

**Comment by tomsteenbakkers** [comment]
Excellent job!

**Comment by tomsteenbakkers** [comment]
I have removed the 0.6.8 version and installed your version using `sudo npm i -g homebridge-mi-aqara-fakegat@latest`. 

After a reboot I see that version 0.6.9 is loaded, I see all the sensors, but not the graph option. Do I need to do something extra?

**Comment by SeydX** [comment]
Wait some Minutes or reinstall the Eve App

**Comment by tomsteenbakkers** [comment]
Reinstalled the Eve app and the graphs are building up 

Thanks for the support 👍

**Comment by tomsteenbakkers** [comment]
@SeydX I have installed your version. I needed to delete the folder persist and accessories. With the ‘old’ accessories some caused Homebridge to crashed because the history parameter could not be read. With a new Home everything is working and the graphs are building up nicely. 

The only thing I notice is that in this version the Xiaomi Gateway is not shown in tha Home app. Does your version excluded the publishing of the Xiaomi Gateway?

**Comment by SeydX** [comment]
Hello,

No i dont modified other part of the Code that  control the Gateway

Maybe you need to modify the config.json and put 'disable': false to the gateway

**Comment by tomsteenbakkers** [comment]
I checked the config.json but nothing brings back the gateway. Maybe I’m doing something wrong. This is entry for the platform:

        {
            "platform": "MiAqaraPlatform",
            "gateways": {
                "286c07fa36ff": "206A7ABB88F54232"
            },
            "defaultValue": {
                "286c07fa36ff": {
                    "Global": {
                        "disable": false
                    }
                }
            }
        }

**Comment by rqui** [comment]
Is there a way to store the sensor data to google drive? I tried to configure it, with the fakegato instructions but I can't get to work... 

Thanks!

**Comment by tomsteenbakkers** [comment]
@SeydX the graphs in the Eve app stopped working for the contact sensor. The sensors do respond to open/close. But the graph is not showing the changes anymore. The temperature sensor is working correct, so it’s only related to the contact and motion sensors. Has this to do with the new update of the Eve app from June 11?

**Comment by lboue** [comment]
Hello,

Could you add fake Elgato history for Lux sensor? For exemple the Gateway_LightSensor. 
History works well for temperature sensor and contact door sensor but not ligt sensor.

Thanks!

**Comment by jresende7** [comment]
When the merge will finally happen ?

**Comment by honkmaster** [comment]
Merge anytime soon?

**Comment by oetelaar24** [comment]
Yes, please merge this, the original has updates and fixes but I don't want to lose the fakegato support!

**Comment by jresende7** [comment]
News ?

**Comment by kalety** [comment]
Hi!, when you upgrade to 0.7.3?. Thanks in advance!

**Comment by x23piracy** [comment]
Hi, please merge this into the project, history data for sensor would be great.

**Comment by SeydX** [comment]
Close. See https://github.com/YinHangCode/homebridge-mi-aqara/pull/269

**Pull request closed without merging**
