### PR TITLE
FakeGato Support - v0.8.1

### PR DESCRIPTION
**Pull request by SeydX**
Fakegato is a module to emulate Elgato Eve history service in Homebridge accessories, so that it will show in Eve.app

Fakegato: https://github.com/simont77/fakegato-history/blob/master/README.md

This will add Fakegato to Temperature/Humidity Sensors (v1/v2), Motion Sensors (v1/v2) and Contact Sensors(v1/v2)

If you do not want to wait for this pull request, you can already install the version with 'Fakegato' as follows

sudo npm i -g homebridge-mi-aqara-fakegato@latest

### CODE REVIEW

**Comment by SeydX** [comment]
Now its rdy to be merged

**Comment by x23piracy** [comment]
Please merge.

**Comment by Martvvliet** [comment]
When I have the humidity and temp sensor together, Only one of the two has the history. This looks to be randomly chosen. Can you explain why this is the case?

**Comment by gielk** [comment]
Can someone make it work and up to date?

**Pull request closed without merging**
